module.exports = {
    VALIDATION_ERROR: 1,
    TOKEN_REQUIRED: 2,
    INVALID_TOKEN: 3,
    MISSING_JWT_SECRET: 4,
    INTERNAL_SERVER_ERROR: 5,
    TOKEN_EXPIRED: 6,
    INVALID_TOKEN_SIGNATURE: 7,
    TOKEN_NOT_ACTIVE: 8,
    INVALID_TOKEN_FORMAT: 9,
    INVALID_TOKEN_SIGNATURE: 10,
    TOKEN_NOT_ACTIVE: 11,
    INVALID_TOKEN_FORMAT: 12,
    INVALID_TOKEN_SIGNATURE: 13,
    TOKEN_NOT_ACTIVE: 14,
    INVALID_TOKEN_FORMAT: 15,
    INVALID_TOKEN_SIGNATURE: 16
};
